apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: robot-env
  name: robot-env
spec:
  containers:
  - image: armdocker.rnd.ericsson.se/proj-edca-dev/robot-env:1.4
    name: robot-env
    command:
    - sh
    - -c
    - --
    args:
    - while true;do sleep 30;done
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}