#
# COPYRIGHT Ericsson 2020
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-edca-catalog.fullname" . }}
  labels:
{{- include "eric-edca-catalog.labels" . | nindent 4 }}
{{- include "eric-edca-catalog.user-labels" . | indent 4 }}
  annotations:
{{- include "eric-edca-catalog.product-info" . | nindent 4 }}
{{- include "eric-edca-catalog.prometheus" . | nindent 4 }}
spec:
{{- if .Values.global }}
{{- if .Values.global.internalIPFamily }}
  ipFamily: {{ .Values.global.internalIPFamily }}
{{- end }}
{{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: eric-edca-catalog
  selector:
    app.kubernetes.io/name: {{ include "eric-edca-catalog.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
