apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-edca-catalog.fullname" . }}-sa
  labels:
{{- include "eric-edca-catalog.labels" . | nindent 4 }}
{{- include "eric-edca-catalog.user-labels" . | indent 4 }}
  annotations:
{{- include "eric-edca-catalog.product-info" . | nindent 4 }}
automountServiceAccountToken: false
